-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.user_profile
(
    user_id uuid NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_profile_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_profile_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_profile
    OWNER to postgres;

ALTER TABLE IF EXISTS public.user_profile
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.user_profile TO anon;

GRANT ALL ON TABLE public.user_profile TO authenticated;

GRANT ALL ON TABLE public.user_profile TO postgres;

GRANT ALL ON TABLE public.user_profile TO service_role;
CREATE POLICY "Users can update their own profile"
    ON public.user_profile
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own profile"
    ON public.user_profile
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = user_id));

CREATE TRIGGER handle_updated_at_profile
    BEFORE UPDATE 
    ON public.user_profile
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TABLE IF NOT EXISTS public.waitlist
(
    user_id uuid NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    linkedin_url text COLLATE pg_catalog."default" NOT NULL,
    responses jsonb NOT NULL DEFAULT '{}'::jsonb,
    can_create_account boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT waitlist_pkey PRIMARY KEY (user_id),
    CONSTRAINT waitlist_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.waitlist
    OWNER to postgres;

ALTER TABLE IF EXISTS public.waitlist
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.waitlist TO anon;

GRANT ALL ON TABLE public.waitlist TO authenticated;

GRANT ALL ON TABLE public.waitlist TO postgres;

GRANT ALL ON TABLE public.waitlist TO service_role;
CREATE POLICY "Users can view their own waitlist entry"
    ON public.waitlist
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = user_id));

CREATE TRIGGER handle_updated_at_waitlist
    BEFORE UPDATE 
    ON public.waitlist
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');
