// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package client

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserEmailSyncHistory(ctx context.Context, userID uuid.UUID) (UserEmailSyncHistory, error)
	GetUserOAuthToken(ctx context.Context, arg GetUserOAuthTokenParams) (UserOauthToken, error)
	GetUserProfileByEmail(ctx context.Context, email string) (UserProfile, error)
	ListOAuthTokensByProvider(ctx context.Context, provider string) ([]UserOauthToken, error)
	ListValidOAuthTokensByProvider(ctx context.Context, provider string) ([]UserOauthToken, error)
	UpsertUserEmailSyncHistory(ctx context.Context, arg UpsertUserEmailSyncHistoryParams) error
	UpsertUserOAuthToken(ctx context.Context, arg UpsertUserOAuthTokenParams) error
}

var _ Querier = (*Queries)(nil)
